version = 0.1

[default.global.parameters]
stack_name = "lifeledger-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.local_start_api.parameters]
env_vars = "env.local.json"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "AppEnv=\"production\" AuthMode=\"cognito\" PersistenceMode=\"dynamodb\" RemindersTableName=\"lifeledger-reminders-auth\" PreferencesTableName=\"lifeledger-preferences-auth\" PushSubscriptionsTableName=\"lifeledger-push-subscriptions-auth\" GoogleClientId=\"your-google-oauth-web-client-id\" GoogleClientSecret=\"your-google-oauth-web-client-secret\" GoogleOAuthRedirectUri=\"https://your-frontend.example.com/\" GoogleCalendarScopes=\"https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly\" VapidPublicKey=\"your-vapid-public-key\" VapidPrivateKey=\"your-vapid-private-key\" VapidSubject=\"mailto:you@example.com\" CorsAllowedOrigins=\"http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,https://lifeledger.jpreinold.com,https://www.lifeledger.jpreinold.com\""
