import type { LifeAdminTemplate } from '../types/template'

export const lifeAdminTemplates: LifeAdminTemplate[] = [
  {
    id: 'birthday-reminder',
    title: 'Birthday reminder',
    category: 'Family',
    targetType: 'birthday',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track birthdays and calculate age when you know the birth year or turning age.',
    suggestedNotes: 'Add the person and any gift or card planning notes.',
    defaultDueDateStrategy: 'choose-date',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Calculates age',
    featured: true,
    filterGroups: ['Smart', 'Dates & People'],
    tags: ['birthday', 'occasion', 'smart', 'age', 'family'],
  },
  {
    id: 'renew-vehicle-registration',
    title: 'Vehicle registration renewal',
    category: 'Car',
    targetType: 'renewal',
    targetKind: 'renewal',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Track a registration renewal date and get reminder context before it is due.',
    suggestedNotes: 'Confirm renewal window and inspection needs before the due date.',
    defaultDueDateStrategy: 'next-renewal',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks renewal',
    renewalItemName: 'Vehicle registration',
    renewalWindowDays: 30,
    featured: true,
    filterGroups: ['Smart', 'Vehicle'],
    tags: ['renewal', 'vehicle', 'registration', 'tag', 'smart'],
  },
  {
    id: 'passport-expiration',
    title: 'Passport expiration',
    category: 'Other',
    targetType: 'renewal',
    targetKind: 'document',
    recommendedRepeat: 'None',
    recommendedPriority: 'High',
    description: 'Track an expiration date and see when it is coming up.',
    suggestedNotes: 'Confirm passport expiration and renewal requirements. Do not store passport numbers here.',
    defaultDueDateStrategy: 'before-expiration',
    defaultReminderTiming: { reminder_lead_value: 3, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks expiration',
    renewalItemName: 'Passport',
    reviewLeadDays: 180,
    featured: true,
    filterGroups: ['Smart', 'Documents'],
    tags: ['passport', 'document', 'expiration', 'renewal', 'smart'],
  },
  {
    id: 'insurance-renewal',
    title: 'Insurance renewal',
    category: 'Finance',
    targetType: 'renewal',
    targetKind: 'renewal',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Track an insurance renewal date for home, auto, pet, or another policy.',
    suggestedNotes: 'Review coverage and premium. Do not store policy numbers or sensitive account details here.',
    defaultDueDateStrategy: 'next-renewal',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks renewal',
    renewalItemName: 'Insurance',
    featured: true,
    filterGroups: ['Smart', 'Finance', 'Home', 'Vehicle'],
    tags: ['insurance', 'renewal', 'home', 'auto', 'pet', 'smart'],
  },
  {
    id: 'free-trial-cancellation',
    title: 'Free trial cancellation',
    category: 'Subscriptions',
    targetType: 'renewal',
    targetKind: 'free_trial',
    recommendedRepeat: 'None',
    recommendedPriority: 'High',
    description: 'Remember to cancel or review before a trial ends.',
    suggestedNotes: 'Confirm trial end date and cancel if you do not want to keep it.',
    defaultDueDateStrategy: 'before-expiration',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'days', reminder_time: '09:00' },
    smartBadge: 'Trial reminder',
    renewalItemName: 'Free trial',
    reviewLeadDays: 1,
    featured: true,
    filterGroups: ['Smart', 'Subscriptions'],
    tags: ['trial', 'free trial', 'cancel', 'subscription', 'smart'],
  },
  {
    id: 'warranty-expiration',
    title: 'Warranty expiration',
    category: 'Home',
    targetType: 'renewal',
    targetKind: 'warranty',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Review coverage before a warranty expires.',
    suggestedNotes: 'Check coverage and decide whether any action is needed before expiration.',
    defaultDueDateStrategy: 'before-expiration',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks expiration',
    renewalItemName: 'Warranty',
    reviewLeadDays: 30,
    featured: true,
    filterGroups: ['Smart', 'Home', 'Documents'],
    tags: ['warranty', 'expiration', 'coverage', 'smart'],
  },
  {
    id: 'change-hvac-filter',
    title: 'Change HVAC filter',
    category: 'Home',
    targetType: 'maintenance',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Track a recurring home maintenance interval and advance it after completion.',
    suggestedNotes: 'Check filter size and replace the filter.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Tracks interval',
    featured: true,
    maintenanceItemName: 'Change HVAC filter',
    maintenanceArea: 'home',
    maintenanceIntervalValue: 3,
    maintenanceIntervalUnit: 'months',
    maintenanceInstructions: 'Check filter size and replace the filter.',
    filterGroups: ['Smart', 'Home', 'Maintenance'],
    tags: ['hvac', 'filter', 'maintenance', 'home', 'smart', 'interval'],
  },
  {
    id: 'document-expiration',
    title: 'Document expiration',
    category: 'Other',
    targetType: 'renewal',
    targetKind: 'document',
    recommendedRepeat: 'None',
    recommendedPriority: 'High',
    description: 'Track a license, permit, certification, or other document expiration date.',
    suggestedNotes: 'Confirm expiration date and renewal requirements. Do not store identification numbers here.',
    defaultDueDateStrategy: 'before-expiration',
    defaultReminderTiming: { reminder_lead_value: 3, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks expiration',
    renewalItemName: 'Document',
    filterGroups: ['Smart', 'Documents'],
    tags: ['document', 'driver license', 'license', 'permit', 'certification', 'expiration', 'passport', 'smart'],
  },
  {
    id: 'certification-renewal',
    title: 'Certification renewal',
    category: 'Other',
    targetType: 'renewal',
    targetKind: 'renewal',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Track a professional or training certification renewal date.',
    suggestedNotes: 'Confirm renewal deadline and requirements. Do not store certificate numbers here.',
    defaultDueDateStrategy: 'next-renewal',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks renewal',
    renewalItemName: 'Certification',
    reviewLeadDays: 30,
    filterGroups: ['Smart', 'Documents'],
    tags: ['certification', 'renewal', 'document', 'smart'],
  },
  {
    id: 'subscription-renewal',
    title: 'Subscription renewal',
    category: 'Subscriptions',
    targetType: 'renewal',
    targetKind: 'subscription',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Track a recurring service or membership renewal date.',
    suggestedNotes: 'Confirm renewal date and decide whether to keep, change, or cancel.',
    defaultDueDateStrategy: 'next-renewal',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Tracks renewal',
    renewalItemName: 'Subscription',
    filterGroups: ['Smart', 'Subscriptions'],
    tags: ['subscription', 'membership', 'renewal', 'smart'],
  },
  {
    id: 'credit-card-annual-fee-review',
    title: 'Credit card annual fee review',
    category: 'Finance',
    targetType: 'renewal',
    targetKind: 'review',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Review whether an annual card fee is still worthwhile before it posts.',
    suggestedNotes: 'Review the account directly. Do not store card numbers, account numbers, or security codes here.',
    defaultDueDateStrategy: 'next-review',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Review date',
    renewalItemName: 'Credit card annual fee',
    reviewLeadDays: 7,
    filterGroups: ['Smart', 'Finance'],
    tags: ['credit card', 'annual fee', 'review', 'renewal', 'finance', 'smart'],
  },
  {
    id: 'pet-vaccination-renewal',
    title: 'Pet vaccination renewal',
    category: 'Family',
    targetType: 'renewal',
    targetKind: 'renewal',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track the next pet vaccination renewal date without storing health records.',
    suggestedNotes: 'Confirm the next due date with your vet. Do not store medical details here.',
    defaultDueDateStrategy: 'next-renewal',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Tracks renewal',
    renewalItemName: 'Pet vaccination',
    filterGroups: ['Smart', 'Dates & People'],
    tags: ['pet', 'vaccination', 'renewal', 'smart'],
  },
  {
    id: 'annual-checkup',
    title: 'Annual checkup',
    category: 'Health',
    targetType: 'maintenance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track a yearly checkup interval and advance it after completion.',
    suggestedNotes: 'Schedule the appointment and keep notes general. Do not store medical details here.',
    defaultDueDateStrategy: 'next-review',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Annual checkup',
    maintenanceArea: 'health',
    maintenanceIntervalValue: 1,
    maintenanceIntervalUnit: 'years',
    filterGroups: ['Smart', 'Health', 'Maintenance'],
    tags: ['appointment', 'checkup', 'health', 'maintenance', 'smart'],
  },
  {
    id: 'dentist-cleaning',
    title: 'Dentist cleaning',
    category: 'Health',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Track a recurring dental cleaning interval without storing medical details.',
    suggestedNotes: 'Schedule cleaning and confirm appointment time.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Dentist cleaning',
    maintenanceArea: 'health',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Health', 'Maintenance'],
    tags: ['dentist', 'cleaning', 'appointment', 'health', 'maintenance', 'smart'],
  },
  {
    id: 'eye-exam',
    title: 'Eye exam',
    category: 'Health',
    targetType: 'maintenance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track a routine eye exam interval and advance it after completion.',
    suggestedNotes: 'Schedule exam and keep notes general.',
    defaultDueDateStrategy: 'next-review',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Eye exam',
    maintenanceArea: 'health',
    maintenanceIntervalValue: 1,
    maintenanceIntervalUnit: 'years',
    filterGroups: ['Smart', 'Health', 'Maintenance'],
    tags: ['eye exam', 'appointment', 'health', 'maintenance', 'smart'],
  },
  {
    id: 'oil-change',
    title: 'Oil change',
    category: 'Car',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Track a date-based oil change interval. Mileage-based reminders are coming later.',
    suggestedNotes: 'Schedule service with a trusted shop. Do not store VIN or license details here.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Oil change',
    maintenanceArea: 'vehicle',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Vehicle', 'Maintenance'],
    tags: ['oil', 'maintenance', 'vehicle', 'car', 'date based', 'smart'],
  },
  {
    id: 'tire-rotation',
    title: 'Tire rotation',
    category: 'Car',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Track a date-based tire rotation interval. Mileage-based reminders are coming later.',
    suggestedNotes: 'Schedule rotation and combine with other routine service if useful.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Tire rotation',
    maintenanceArea: 'vehicle',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Vehicle', 'Maintenance'],
    tags: ['tire', 'maintenance', 'vehicle', 'car', 'date based', 'smart'],
  },
  {
    id: 'test-smoke-detectors',
    title: 'Test smoke detectors',
    category: 'Home',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'High',
    description: 'Track a home safety maintenance interval and advance it after completion.',
    suggestedNotes: 'Test alarms and confirm each detector responds.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Tracks interval',
    maintenanceItemName: 'Test smoke detectors',
    maintenanceArea: 'home',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Home', 'Maintenance'],
    tags: ['smoke detector', 'safety', 'maintenance', 'home', 'smart'],
  },
  {
    id: 'clean-dryer-vent',
    title: 'Clean dryer vent',
    category: 'Home',
    targetType: 'maintenance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track a yearly dryer vent cleaning interval.',
    suggestedNotes: 'Clean lint buildup and confirm airflow.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Clean dryer vent',
    maintenanceArea: 'home',
    maintenanceIntervalValue: 1,
    maintenanceIntervalUnit: 'years',
    filterGroups: ['Smart', 'Home', 'Maintenance'],
    tags: ['dryer vent', 'maintenance', 'home', 'smart'],
  },
  {
    id: 'clean-gutters',
    title: 'Clean gutters',
    category: 'Home',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Track a recurring gutter cleaning interval.',
    suggestedNotes: 'Clear debris and check downspouts.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Clean gutters',
    maintenanceArea: 'home',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Home', 'Maintenance'],
    tags: ['gutters', 'maintenance', 'home', 'smart'],
  },
  {
    id: 'replace-fridge-water-filter',
    title: 'Replace fridge water filter',
    category: 'Home',
    targetType: 'maintenance',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'Track a recurring refrigerator water filter interval.',
    suggestedNotes: 'Replace the filter and reset the fridge indicator if needed.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Replace fridge water filter',
    maintenanceArea: 'home',
    maintenanceIntervalValue: 6,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Home', 'Maintenance'],
    tags: ['fridge', 'water filter', 'maintenance', 'home', 'smart'],
  },
  {
    id: 'pet-flea-tick-medicine',
    title: 'Pet flea/tick medicine',
    category: 'Family',
    targetType: 'maintenance',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Track a monthly pet care interval without storing medical details.',
    suggestedNotes: 'Confirm timing with your vet and keep notes general.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Pet flea/tick medicine',
    maintenanceArea: 'pet',
    maintenanceIntervalValue: 1,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Dates & People', 'Maintenance'],
    tags: ['pet', 'flea', 'tick', 'medicine', 'maintenance', 'smart'],
  },
  {
    id: 'pet-heartworm-medicine',
    title: 'Pet heartworm medicine',
    category: 'Family',
    targetType: 'maintenance',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Track a monthly pet care interval without storing medical details.',
    suggestedNotes: 'Confirm timing with your vet and keep notes general.',
    defaultDueDateStrategy: 'next-service',
    defaultReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    smartBadge: 'Maintenance',
    maintenanceItemName: 'Pet heartworm medicine',
    maintenanceArea: 'pet',
    maintenanceIntervalValue: 1,
    maintenanceIntervalUnit: 'months',
    filterGroups: ['Smart', 'Dates & People', 'Maintenance'],
    tags: ['pet', 'heartworm', 'medicine', 'maintenance', 'smart'],
  },
  {
    id: 'review-subscriptions',
    title: 'Review subscriptions',
    category: 'Subscriptions',
    targetType: 'generic',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Create a recurring reminder to review active subscriptions.',
    suggestedNotes: 'Check active subscriptions and cancel anything unused.',
    defaultDueDateStrategy: 'next-review',
    smartBadge: 'Generic',
    filterGroups: ['Subscriptions', 'Finance'],
    tags: ['review', 'subscriptions', 'budget', 'generic'],
  },
  {
    id: 'budget-review',
    title: 'Budget review',
    category: 'Finance',
    targetType: 'generic',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Create a recurring reminder to review income, expenses, and upcoming obligations.',
    suggestedNotes: 'Review spending, upcoming bills, and savings goals.',
    defaultDueDateStrategy: 'next-review',
    smartBadge: 'Generic',
    filterGroups: ['Finance'],
    tags: ['budget', 'review', 'finance', 'generic'],
  },
  {
    id: 'tax-prep-reminder',
    title: 'Tax prep reminder',
    category: 'Finance',
    targetType: 'generic',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Create a reminder to gather tax documents before filing deadlines arrive.',
    suggestedNotes: 'Gather forms and schedule prep time. Do not store tax IDs or sensitive documents here.',
    defaultDueDateStrategy: 'before-expiration',
    smartBadge: 'Generic',
    filterGroups: ['Finance', 'Documents'],
    tags: ['taxes', 'documents', 'finance', 'deadline', 'generic'],
  },
  {
    id: 'anniversary-reminder',
    title: 'Anniversary reminder',
    category: 'Family',
    targetType: 'generic',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Create a yearly reminder for an anniversary or meaningful date.',
    suggestedNotes: 'Add the occasion and any planning notes.',
    defaultDueDateStrategy: 'choose-date',
    smartBadge: 'Generic',
    filterGroups: ['Dates & People'],
    tags: ['anniversary', 'occasion', 'family', 'date', 'generic'],
  },
  {
    id: 'gift-planning-reminder',
    title: 'Gift planning reminder',
    category: 'Family',
    targetType: 'generic',
    recommendedRepeat: 'None',
    recommendedPriority: 'Low',
    description: 'Create a reminder to plan ahead for a gift, card, or celebration.',
    suggestedNotes: 'Note the occasion and next planning step.',
    defaultDueDateStrategy: 'choose-date',
    smartBadge: 'Generic',
    filterGroups: ['Dates & People'],
    tags: ['gift', 'planning', 'occasion', 'family', 'generic'],
  },
  {
    id: 'personal-admin-review',
    title: 'Personal admin review',
    category: 'Other',
    targetType: 'generic',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Create time to review renewals, maintenance tasks, and recurring responsibilities.',
    suggestedNotes: 'Review upcoming reminders and add anything missing.',
    defaultDueDateStrategy: 'next-review',
    smartBadge: 'Generic',
    filterGroups: ['Finance', 'Maintenance'],
    tags: ['personal admin', 'life admin', 'review', 'recurring responsibilities', 'generic'],
  },
  {
    id: 'vehicle-maintenance-by-mileage',
    title: 'Vehicle maintenance by mileage',
    category: 'Car',
    targetType: 'comingSoon',
    comingSoonLabel: 'Mileage-based reminders',
    recommendedRepeat: 'None',
    recommendedPriority: 'Medium',
    description: 'A future template for maintenance intervals based on mileage instead of dates.',
    suggestedNotes: '',
    smartBadge: 'Coming soon',
    filterGroups: ['Coming soon', 'Vehicle', 'Maintenance'],
    tags: ['vehicle', 'mileage', 'maintenance', 'coming soon'],
  },
]