import type { LifeAdminTemplate } from '../types/template'

export const lifeAdminTemplates: LifeAdminTemplate[] = [
  {
    id: 'renew-vehicle-registration',
    title: 'Renew vehicle registration',
    category: 'Car',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Track the next vehicle registration or tag renewal deadline.',
    suggestedNotes: 'Confirm renewal window, inspection needs, and payment method before the due date.',
    defaultDueDateStrategy: 'next-renewal',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    tags: ['renewal', 'vehicle'],
  },
  {
    id: 'oil-change',
    title: 'Oil change',
    category: 'Car',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Keep routine oil service from slipping past the recommended window.',
    suggestedNotes: 'Check mileage and schedule service with a trusted shop.',
    defaultDueDateStrategy: 'next-service',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    tags: ['maintenance', 'vehicle'],
  },
  {
    id: 'tire-rotation',
    title: 'Tire rotation',
    category: 'Car',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Plan regular tire rotation for safer wear and handling.',
    suggestedNotes: 'Check mileage and combine with other routine service if useful.',
    defaultDueDateStrategy: 'next-service',
    tags: ['maintenance', 'vehicle'],
  },
  {
    id: 'auto-insurance-renewal',
    title: 'Auto insurance renewal',
    category: 'Car',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Remember to review and renew auto coverage before the renewal date.',
    suggestedNotes: 'Review coverage and premium. Do not store policy numbers or sensitive account details here.',
    defaultDueDateStrategy: 'next-renewal',
    tags: ['renewal', 'insurance'],
  },
  {
    id: 'driver-license-renewal',
    title: 'Driver license renewal',
    category: 'Car',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Avoid missing a driver license expiration or renewal window.',
    suggestedNotes: 'Confirm renewal requirements and bring required identification.',
    defaultDueDateStrategy: 'before-expiration',
    tags: ['renewal', 'document'],
  },
  {
    id: 'annual-checkup',
    title: 'Annual checkup',
    category: 'Health',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Set a yearly reminder to schedule a general checkup.',
    suggestedNotes: 'Schedule the appointment and prepare general questions. Do not store medical details here.',
    defaultDueDateStrategy: 'next-review',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'months', reminder_time: '09:00' },
    tags: ['appointment', 'review'],
  },
  {
    id: 'dentist-cleaning',
    title: 'Dentist cleaning',
    category: 'Health',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Keep dental cleanings on your radar.',
    suggestedNotes: 'Schedule cleaning and confirm appointment time.',
    defaultDueDateStrategy: 'next-service',
    tags: ['appointment'],
  },
  {
    id: 'eye-exam',
    title: 'Eye exam',
    category: 'Health',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Remember routine eye exam timing.',
    suggestedNotes: 'Schedule exam and check whether new glasses or contacts are needed.',
    defaultDueDateStrategy: 'next-review',
    tags: ['appointment'],
  },
  {
    id: 'prescription-refill-reminder',
    title: 'Prescription refill reminder',
    category: 'Health',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'High',
    description: 'Remember to check refill timing without storing prescription details.',
    suggestedNotes: 'Check refill status through the pharmacy or provider. Do not store medication details here.',
    defaultDueDateStrategy: 'choose-date',
    tags: ['refill'],
  },
  {
    id: 'change-hvac-filter',
    title: 'Change HVAC filter',
    category: 'Home',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Keep air filters changed on a regular schedule.',
    suggestedNotes: 'Check filter size and replace the filter.',
    defaultDueDateStrategy: 'next-service',
    tags: ['maintenance'],
  },
  {
    id: 'test-smoke-detectors',
    title: 'Test smoke detectors',
    category: 'Home',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'High',
    description: 'Set a routine safety reminder for smoke detector testing.',
    suggestedNotes: 'Test alarms and confirm each detector responds.',
    defaultDueDateStrategy: 'next-service',
    tags: ['safety', 'maintenance'],
  },
  {
    id: 'replace-smoke-detector-batteries',
    title: 'Replace smoke detector batteries',
    category: 'Home',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Plan battery replacement before alarms start chirping.',
    suggestedNotes: 'Replace batteries and test each detector afterward.',
    defaultDueDateStrategy: 'next-service',
    tags: ['safety', 'maintenance'],
  },
  {
    id: 'home-insurance-renewal',
    title: 'Home insurance renewal',
    category: 'Home',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Review and renew home insurance before the renewal date.',
    suggestedNotes: 'Review coverage and premium. Do not store policy numbers or sensitive account details here.',
    defaultDueDateStrategy: 'next-renewal',
    tags: ['renewal', 'insurance'],
  },
  {
    id: 'pest-control-reminder',
    title: 'Pest control reminder',
    category: 'Home',
    recommendedRepeat: 'Quarterly',
    recommendedPriority: 'Medium',
    description: 'Remember seasonal or recurring pest control tasks.',
    suggestedNotes: 'Schedule service or complete the planned home treatment.',
    defaultDueDateStrategy: 'next-service',
    tags: ['maintenance'],
  },
  {
    id: 'review-subscriptions',
    title: 'Review subscriptions',
    category: 'Finance',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Review recurring charges and cancel anything no longer useful.',
    suggestedNotes: 'Check active subscriptions and note any cancellations to make.',
    defaultDueDateStrategy: 'next-review',
    tags: ['review', 'subscriptions'],
  },
  {
    id: 'credit-report-check',
    title: 'Credit report check',
    category: 'Finance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Set a reminder to review credit reports for accuracy.',
    suggestedNotes: 'Use official credit report sources. Do not store SSNs or account numbers here.',
    defaultDueDateStrategy: 'next-review',
    tags: ['review'],
  },
  {
    id: 'budget-review',
    title: 'Budget review',
    category: 'Finance',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Reserve time to review income, expenses, and upcoming obligations.',
    suggestedNotes: 'Review spending, upcoming bills, and savings goals.',
    defaultDueDateStrategy: 'next-review',
    tags: ['review'],
  },
  {
    id: 'tax-prep-reminder',
    title: 'Tax prep reminder',
    category: 'Finance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Start gathering tax documents before filing deadlines arrive.',
    suggestedNotes: 'Gather forms and schedule prep time. Do not store tax IDs or sensitive documents here.',
    defaultDueDateStrategy: 'before-expiration',
    tags: ['taxes', 'documents'],
  },
  {
    id: 'credit-card-annual-fee-reminder',
    title: 'Credit card annual fee reminder',
    category: 'Finance',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Remember to review whether an annual card fee is still worthwhile.',
    suggestedNotes: 'Review the account directly. Do not store card numbers or security codes here.',
    defaultDueDateStrategy: 'next-renewal',
    tags: ['renewal', 'review'],
  },
  {
    id: 'birthday-reminder',
    title: 'Birthday reminder',
    category: 'Family',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Remember an important birthday each year.',
    suggestedNotes: 'Add the person and any gift or card planning notes.',
    defaultDueDateStrategy: 'choose-date',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    tags: ['occasion'],
  },
  {
    id: 'anniversary-reminder',
    title: 'Anniversary reminder',
    category: 'Family',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Track an anniversary or meaningful yearly date.',
    suggestedNotes: 'Add the occasion and any planning notes.',
    defaultDueDateStrategy: 'choose-date',
    tags: ['occasion'],
  },
  {
    id: 'gift-planning-reminder',
    title: 'Gift planning reminder',
    category: 'Family',
    recommendedRepeat: 'None',
    recommendedPriority: 'Low',
    description: 'Plan ahead for a gift, card, or celebration.',
    suggestedNotes: 'Note the occasion and next planning step.',
    defaultDueDateStrategy: 'choose-date',
    tags: ['planning'],
  },
  {
    id: 'free-trial-cancellation-reminder',
    title: 'Free trial cancellation reminder',
    category: 'Subscriptions',
    recommendedRepeat: 'None',
    recommendedPriority: 'High',
    description: 'Avoid surprise charges before a free trial converts.',
    suggestedNotes: 'Confirm trial end date and cancel if you do not want to keep it.',
    defaultDueDateStrategy: 'before-expiration',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'days', reminder_time: '09:00' },
    tags: ['cancellation', 'subscription'],
  },
  {
    id: 'annual-subscription-renewal',
    title: 'Annual subscription renewal',
    category: 'Subscriptions',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'Medium',
    description: 'Review annual subscriptions before renewal.',
    suggestedNotes: 'Confirm renewal date and decide whether to keep, change, or cancel.',
    defaultDueDateStrategy: 'next-renewal',
    suggestedReminderTiming: { reminder_lead_value: 1, reminder_lead_unit: 'weeks', reminder_time: '09:00' },
    tags: ['renewal', 'subscription'],
  },
  {
    id: 'monthly-subscription-review',
    title: 'Monthly subscription review',
    category: 'Subscriptions',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Review monthly subscriptions and recurring app charges.',
    suggestedNotes: 'Check active subscriptions and cancel anything unused.',
    defaultDueDateStrategy: 'next-review',
    tags: ['review', 'subscription'],
  },
  {
    id: 'important-document-renewal',
    title: 'Important document renewal',
    category: 'Other',
    recommendedRepeat: 'Yearly',
    recommendedPriority: 'High',
    description: 'Track a passport, permit, certification, or other important document renewal.',
    suggestedNotes: 'Confirm renewal deadline and required documents. Do not store identification numbers here.',
    defaultDueDateStrategy: 'before-expiration',
    tags: ['renewal', 'document'],
  },
  {
    id: 'warranty-expiration-reminder',
    title: 'Warranty expiration reminder',
    category: 'Other',
    recommendedRepeat: 'None',
    recommendedPriority: 'Low',
    description: 'Remember to review a warranty before it expires.',
    suggestedNotes: 'Check coverage and decide whether any action is needed before expiration.',
    defaultDueDateStrategy: 'before-expiration',
    tags: ['warranty'],
  },
  {
    id: 'personal-admin-review',
    title: 'Personal admin review',
    category: 'Other',
    recommendedRepeat: 'Monthly',
    recommendedPriority: 'Medium',
    description: 'Set aside time to review renewals, maintenance tasks, and recurring responsibilities.',
    suggestedNotes: 'Review upcoming reminders and add anything missing.',
    defaultDueDateStrategy: 'next-review',
    tags: ['review'],
  },
]
